sudo: false
dist: trusty
language: node_js
node_js:
  - '8'
  - '7'
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  slack: beebright:DxPZYpdd26Ni3vFGQFKngXK3