language: node_js
sudo: false
dist: trusty
node_js:
  - '8'
  - '7'
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - develop
    # - "/^release\\/.*$/"
    - master
install:
  # - yarn
script:
  - yarn build
  - yarn test
  - yarn travis
notifications:
  slack: beebright:DxPZYpdd26Ni3vFGQFKngXK3