language: node_js
sudo: false
dist: trusty
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - develop
  # - "/^release\\/.*$/"  
  - master
install:
  # - yarn 
script:
- yarn build
- yarn test
- yarn travis
deploy:
  provider: s3
  access_key_id: AKIAIA2J7HXUI52NHMHA
  secret_access_key:
    secure: JPDcEKISOrS4YK31WC/v0Oo8/tjNoDINiz0W59ioZkMGrDDgvQkBxUJV/n0kYy2PBhDRtRqpC5sj8T8FkvXU2/DELihj/4laIDtG+annphRhvKAmjuXxHlBxzC6UfLoPSD/xvMUR43EQsMJLfSkN2mSSD1caKkq4BvEig2bXsyHCewmtsUY/R8kD/91zxmU5dW0RGxJuy8KOxe32w36/jlYSOlFYBcoSAnIOUr+c8tsiM5KUufAyIC4AYFKiaW/eMXPV0YtBk4dP3UhphNM6dEqV0zTM7k3sgYFrIEFbUxLz4QN3pnzAxR9U04SQ4/1wYQMWGwtlNyM7ouCtFWtkdA6pLo47+4pe/MMI4yMi4NonvyQK4FE7GSB1OMOqiTOqnFr+DpfUxhjWCURHlTnygyISVMXHTBRF/prTL5QTM5RMon7sri7ovR67IoMHzNojGl9hsWL0ElDirh5V6A62MliajZGr2xQmwivNCqhCrqqSKjN9j+NHNqpieSL9XkePHra5+eu7W319ScAbC83s5sj0j1byl8vvYGfC0EujxCYnBS+RYxYNLPDGxnQzmVh78BxetuwvhLZJO+4AfMDnSyIwuuQAGSnC6zLABuZpyP/tXzUaottqOqJQtBlI95gGvQ4Z7F+aN7S6T9OfPEkTVATtbaL1wQBSEF1vFIJoTZo=
  bucket: bright-travis-deploy
  local-dir: dist
  acl: private
  on:
    repo: bebright/slack-demo
notifications:
  slack: beebright:DxPZYpdd26Ni3vFGQFKngXK3
